pipeline{
    agent any
    stages{
 
        stage("Git Checkout "){
            steps{
                git branch: 'main',
                credentialsId: 'rupinder-on-github',
                url: 'git@github.com:rupinder-on-github/knowledgetub2-ec2.git'
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}